// Redmine REST API response type
// autogenerated by https://mholt.github.io/json-to-go/

package service

import "time"

type IssuesResponse struct {
	Issues []struct {
		ID      int `json:"id"`
		Project struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"project"`
		Tracker struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"tracker"`
		Status struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"status"`
		Priority struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"priority"`
		Author struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"author"`
		Category struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"category"`
		FixedVersion struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"fixed_version"`
		Subject        string    `json:"subject"`
		Description    string    `json:"description"`
		StartDate      string    `json:"start_date"`
		DoneRatio      int       `json:"done_ratio"`
		IsPrivate      bool      `json:"is_private"`
		EstimatedHours float64   `json:"estimated_hours"`
		CreatedOn      time.Time `json:"created_on"`
		UpdatedOn      time.Time `json:"updated_on"`
		ClosedOn       time.Time `json:"closed_on"`
	} `json:"issues"`
	TotalCount int `json:"total_count"`
	Offset     int `json:"offset"`
	Limit      int `json:"limit"`
}

type ProjectsResponse struct {
	Projects []struct {
		ID             int       `json:"id"`
		Name           string    `json:"name"`
		Identifier     string    `json:"identifier"`
		Description    string    `json:"description"`
		Status         int       `json:"status"`
		IsPublic       bool      `json:"is_public"`
		InheritMembers bool      `json:"inherit_members"`
		CreatedOn      time.Time `json:"created_on"`
		UpdatedOn      time.Time `json:"updated_on"`
	} `json:"projects"`
	TotalCount int `json:"total_count"`
	Offset     int `json:"offset"`
	Limit      int `json:"limit"`
}
